1. What Linear Regression training algorithm can you use if you have a training set with millions of features?


Lasso and Elastic Net help to reduce the importance of useless features, by lowering there weights. But if the number of traning instances is less than the number of features, or several features are stronly correlated then use Elastic Net because it behaves less erratically. 

2. Suppose the features in your training set have very different scales. What algorithms might suffer from this, and how? What can you do about it?

When using Gradient Descent algorithms on MSE cost function if your training data is not scaled you will create a elongated surface. Since you are giving it a learning rate (i.e. steps) to decrease the cost function if the features are not scaled it will take longer to reach its minimum on those features that have larger values and ranges.
Also when using the PolynomialFeatures class on your training set after you fit_transform your data you should use the scale method. And last but not least you should scale data for most of your regularized models, like Ridge and lasso. Ridge Regression and others are sensitive to the scale of the input features. StandardScaler class has a fit_transform method to scale you training data.

3. Can Gradient Descent get stuck in a local minimum when training a Logistic Regression model?

The cost function for the Logistic Regression model is convex, so Gradient Descent(or any other optimization algorithm) is guaranteed to find the global minimum, as long as the learning rate is not too large and you wait long enough. 

4. Do all Gradient Descent algorithms lead to the same model provided you let them run long enough?

No. Batch Gradient Descent will settle to the global minimum but Stochastic and mini_Batch will bounce around the global minimum. But with the last two you can write a function called the learning schedule that gradually lowers the learning rate so it settles at a minimum. But there are problems with that approach and if you lower you rate to fast you might find yourself in a local minimum.

5. Suppose you use Batch Gradient Descent and you plot the validation error at every epoch. If you notice the the validation error consistently goes up, what is likely going on? How can you fix this? 

If your learning rate is too high the algorithm diverges, jumping all over the place and can actually go farther and farther away from the solution. But if the training errors are not going up then you have overfitted the model and should consider reducing the number of features or look at the degrees of freedom.

6. Is it a good idea to stop Mini-batch Gradient Descent immediately when the validation error goes up?

No. Like Stochasic Gradient, Mini-batch will jump around but since you are training it on more than one instance per interval you are going to find the minimum faster than the Stochastic method. But remember to save your theta on a regular basis. (Look more into this, should be able to save for a reason not just randomly, possibly checking the cost function)

7. Which Gradient Descent algorithm(among those discussed) will reach the vicinity of the optimal solution the fastest? Which will actually converge? How can you make the others converge as well?


Since mini-batch uses a set of training instances it gets a performance boost from hardware optimization of matrix operations, especially when using GPUs. Batch will actually converge to the optimal model but you can create a function for the learning rate that reduces the size of the steps it takes towards the end. But you do risk being caught in a local minimum.

8. Suppose you are using Polynomial Regression. You plot the learning curves and notice that there is a large gap between the training error and the validation error. What is happening? What are three ways to solve this?

If your training error is much less that your validation error than you are overfitting the model. Since you set the degrees of freedom when you instantiate your PolynomialFeatures object you can reduce the degrees before you call the fit_transform method. Another way to reduce the validation error is to use a larger training set. Also if you are just using a plain linear regression model you could use one of the regularized models like Ridge or Lasso Regression. 

9. Suppose you are using Ridge Regression and you notice that the training error and the validation error are almost equal and fairly high. Would you say that the model suffers from high bias or high variance? Should you increase the regularization hyperparameter $\alpha$ or reduce it?

A model that underfits the training data will have a high validation error and training error. A high-bias model is most likey to underfit the training data. The regularizatin hyperparameter $\alpha$ should be increased. If the model had a high variance that means that it is overly sensitive to the training data's variances or outliers, thus overfitting the model. The model would than want a reduction in its $\alpha$

10. Why would you want to use:
    

Ridge Regression over plain Linear Regression(ie without any regularization)?

It's almost always preferable to have a least a little bit of regulariztion, so it best to avoid plain Linear Regression. 

Lasso instead of Ridge Regression?

An important characteristic of Lasso Regression is that it tends to completely eliminate the least important features by setting there weights to zero. If you feel some of your features are not important than you Lasso instead of Ridge

Elastic instead of Lasso?

Elastic Net has a mix ratio term r that is set to the amount of Lasso Regression you want in your model. If it is set to r =0 , then it is equavalent to Ridge Regression and when it is set to r = 1, then it is Lasso. Elastic Net is usually preferred over Lassom but especially when the number of features is greater than the number of training instances or when several of the features are strongly correlated.

11. Suppose you want to classify pictures as outdoor/indoor and daytime/nighttime. Should you implement two Logistic Regression classifiers or one Softmax Regression classifier?

You would need to implement two Logistic Regression classifiers. Softmax Regression classifer classifies mutually exclusive class. Since you could have an indoor daytime picture or an outdoor daytime picture the classes would not be mutually exclusive

12. Implement Batch Gradient Descent with early stopping for Softmax Regression(without using Scikit-Learn)

Gradient Decent step

$\theta^{(next step)}$  = $\theta$ - $n$$\nabla_{\theta}$MSE($\theta$)

Above is the gradient descent step for a linear models cost function. Minimizing the cost function for Softmax is called cross entropy.

J($\Theta$) = -$\frac{1}{m}$$\sum_{i=1}^{m}$$\sum_{k=1}^{K}$$y_{k}^{(i)}$log($\hat{p}_{k}^{(i)}$)

The gradient vector of this cost function with respect to $\theta^{(k)}$ is

$\nabla_{\theta}{k}$ J($\Theta$) = $\frac{1}{m}$$\sum_{i=1}^{m}$($\hat{p}_{k}^{(i)}$ - $y_{k}^{(i)}$)x$^{(i)}$

Load data from sklearn

In [1]:

from sklearn import datasets
iris = datasets.load_iris()
list(iris.keys())

['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename']

In [2]:
data = iris["data"][:, (2,3)]
target_values = iris["target"]
target_values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
# creating a column with all values equal to 1 for our bias theta
import numpy as np
X_data = np.c_[np.ones([len(data),1]), data]

In [4]:
# Creating a seed for reproducible results
np.random.seed(24)


In [5]:
#first creating a test set
# note that my X_val will not be the 20 of the whole training set like above
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_data, target_values, test_size = .20)


In [6]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = .20)

The target_values were an array of 0,1,2 s. But for classification we need each of those values in their own column since they disinctly identify a class and do not represent numerical value. 

In [13]:
def oneHot(y):
    m = len(y)
    n_classes = y.max() +1
    #creating a m by 3 array of zeros
    target = np.zeros((m,n_classes))
    # for each row of the target set the column(the y value) equal to one
    #numpy.arange([start, ]stop, [step, ]dtype=None)
    target[np.arange(m), y] = 1
    return target

In [14]:
#convert our target values
y_test_one_hot = oneHot(y_test)
y_train_one_hot = oneHot(y_train)
y_val_one_hot = oneHot(y_val)
y_val_one_hot

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

Our Softmax function. remeber $s_{k}(x))$ is a different function so lets first define a function
to deal just with the outside part

$\hat{p}_k$ = $\sigma$(s(x))$_{k}$ = $\frac{exp(s_{k}(x))}{\sum_{j=1}^{K} exp(s_{j}(x))}$

In [9]:
# what we pass in, is our Softmax score for class k
def softmax(logits):
    exps = np.exp(logits)
    sum_exps = np.sum(exps, axis =1, keepdims = True)
    return exps/sum_exps

In [10]:
n_inputs = X_train.shape[1]# gives us the number of theta terms
                           # one for the bias term and one for width and length
n_outputs = len(np.unique(y_train)) # gives us the number of classes    

In [16]:
n_inputs
n_outputs

3

In [20]:
# to train our model
eta = .01 # our learning rate
n_iterations = 5001
m = len(X_train)
epsilon = 1e-7 # added for when our projected probability is 0. if we add this time number we wont get NaN values

Theta = np.random.randn(n_inputs, n_outputs)# creating a matrix theta instead of a array because instead 
                                            # of just one class we have multiple. each class gets its own
                                            # array of theta weights

for iteration in range(n_iterations):
    # okay I would have Theta tranposed then dot X_train ??
    logits = X_train.dot(Theta)
    Y_proba = softmax(logits)
    # this is the Cross entropy cost function
    # the Y_train_one_hot is the expected and the Y_proba is the calculated
    # remember we add epsilon just to stop a NaN for log of zero
    loss = -np.mean(np.sum(y_train_one_hot * np.log(Y_proba +epsilon), axis = 1))
    error = Y_proba - y_train_one_hot
    if iteration % 500 == 0:
        print(iteration, loss)
    # this is the Cross entropy gradient vector for class k
    # again this is backwards from what you would have done
    gradients = 1/m * X_train.T.dot(error)
    Theta = Theta - eta *gradients

0 3.2837418339674245
500 0.8641262387549173
1000 0.7080205759817026
1500 0.6160746040125203
2000 0.5565347688837092
2500 0.5145050284731898
3000 0.4827841976929624
3500 0.4576199616158299
4000 0.4369013316456087
4500 0.41935763552680133
5000 0.4041788923815168


In [21]:
# that is it the soft max model is train lets look at the matrix for model parameters of each class
Theta

array([[ 4.13214623,  0.44771909, -1.65883437],
       [-0.38694137,  0.7041692 ,  0.44634073],
       [-2.51712208, -1.32616406,  0.84978724]])

In [24]:
logits = X_test.dot(Theta)
Y_proba = softmax(logits)
y_predict = np.argmax(Y_proba, axis = 1)
accuracy_score = np.mean(y_predict == y_test)
accuracy_score

1.0